!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/itsmaleeq/image/upload/v1554323066/itsmaleeq-2.png" alt="Mark Essien">
                        <h6>Babajide Abdulmaleek Onayemi</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/itsMaleeq" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/CodeLeeq" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@itsmaleeq" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I studied Information Technology at the Eastern Mediterranean University of Turkish Republic of Northern Cyprus. 
                        Seek a junior- intermediate contract, remote or full time role in the areas of mobile app development 
                        or web development. I strive to help companies succeed with their business goals using my diverse experience
                         and skill set. My long term goal is to be a Chief Technology Officer of a successful company</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML | CSS | Android</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
